### ISSUE TITLE
感觉有些时候没有加载出来  划着划着就显示出来了 划着划着又不显示了。 

### ISSUE THREAD

**Issue by SomnusWu** [iielse/DemoProjects#4]
九宫格布局 界面

**Comment by iielse** [comment]
非常可能是`MessagePicturesLayout`的`notifyDataChanged` 实现方式->执行效率性能不太好，导致看起来有闪烁，哎，蛋疼。

**Comment by SomnusWu** [comment]
你现在给的data都是有图片的情况  我现在是某一个item没有图片   ，滑动几次MessagePicturesLayout 就没有显示了

**Comment by iielse** [comment]
```
private void notifyDataChanged() {
        ...
        if (thumbList == null || thumbList.size() < 1) {
            setVisibility(View.GONE);
            return;
        } else {
            setVisibility(View.VISIBLE);
        }
}
```
我这里有设置 `setVisibility(View.VISIBLE);` 应该不会出现该出来的地方没出来，不该出来的地方出来的情况了吧。而且我刚才自己测试的时候有注释过一组 `pictureThumbList`的数据，上下滑动并没有出现你说的情况啊

**Comment by iielse** [comment]
No response. Closing.
